/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StockInRouteImport } from './routes/stock-in'
import { Route as StockOutRouteImport } from './routes/stock-out'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StockInRoute = StockInRouteImport.update({
  id: '/stock-in',
  path: '/stock-in',
  getParentRoute: () => rootRouteImport,
} as any)
const StockOutRoute = StockOutRouteImport.update({
  id: '/stock-out',
  path: '/stock-out',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/stock-in': typeof StockInRoute
  '/stock-out': typeof StockOutRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/stock-in': typeof StockInRoute
  '/stock-out': typeof StockOutRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/stock-in': typeof StockInRoute
  '/stock-out': typeof StockOutRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/stock-in' | '/stock-out'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/stock-in' | '/stock-out'
  id: '__root__' | '/' | '/stock-in' | '/stock-out'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StockInRoute: typeof StockInRoute
  StockOutRoute: typeof StockOutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock-in': {
      id: '/stock-in'
      path: '/stock-in'
      fullPath: '/stock-in'
      preLoaderRoute: typeof StockInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock-out': {
      id: '/stock-out'
      path: '/stock-out'
      fullPath: '/stock-out'
      preLoaderRoute: typeof StockOutRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StockInRoute: StockInRoute,
  StockOutRoute: StockOutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
